import {fireEvent,render,screen} from "@testing-library/react";
import {describe,expect,it} from "vitest";
import BmiCalculatorUi from "./ui";
describe("BmiCalculatorUi",()=>{
 it("입력 전에 연령별 기준과 분리 이유를 설명한다",()=>{render(<BmiCalculatorUi/>);expect(screen.getByRole("heading",{name:"연령에 따라 이렇게 구분해요"})).toBeInTheDocument();expect(screen.getByText("왜 어린이·청소년은 성인 기준과 다를까요?")).toBeInTheDocument();expect(screen.getByText("만 2세 이상 ~ 만 19세 미만")).toBeInTheDocument();expect(screen.queryByText("현재 적용")).not.toBeInTheDocument();});
 it("소아 예시에서 이해하기 쉬운 또래 위치와 통계 상세를 표시한다",()=>{render(<BmiCalculatorUi/>);fireEvent.click(screen.getByRole("button",{name:"소아 예시"}));expect(screen.getByText("현재 적용")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"BMI 계산하기"}));expect(screen.getByText(/또래 100명 중 낮은 쪽부터/)).toBeInTheDocument();expect(screen.getByText("통계 상세 보기")).toBeInTheDocument();expect(screen.getByRole("heading",{name:"계산 상세"})).toBeInTheDocument();expect(screen.getByText("목표 체중이나 감량 권고가 아닙니다.",{exact:false})).toBeInTheDocument();});
 it("성인 결과에는 전체 BMI 기준표와 현재 위치를 표시한다",()=>{render(<BmiCalculatorUi/>);fireEvent.change(screen.getByLabelText(/생년월일/),{target:{value:"1990-01-01"}});fireEvent.change(screen.getByLabelText(/^키/),{target:{value:"170"}});fireEvent.change(screen.getByLabelText(/^체중/),{target:{value:"80"}});fireEvent.click(screen.getByRole("button",{name:"BMI 계산하기"}));expect(screen.getByRole("heading",{name:"성인 BMI 기준표"})).toBeInTheDocument();expect(screen.getByText("현재 위치")).toBeInTheDocument();});
 it("허리둘레는 성인에게만 보이고 소아로 바꾸면 값을 제거한다",()=>{render(<BmiCalculatorUi/>);const birth=screen.getByLabelText(/생년월일/);expect(screen.queryByLabelText(/허리둘레/)).not.toBeInTheDocument();fireEvent.change(birth,{target:{value:"1990-01-01"}});const waist=screen.getByLabelText(/허리둘레/);fireEvent.change(waist,{target:{value:"88"}});fireEvent.change(birth,{target:{value:"2014-01-01"}});expect(screen.queryByLabelText(/허리둘레/)).not.toBeInTheDocument();fireEvent.change(birth,{target:{value:"1990-01-01"}});expect(screen.getByLabelText(/허리둘레/)).toHaveValue("");});
 it("빈 필수값에는 오류를 표시한다",()=>{render(<BmiCalculatorUi/>);fireEvent.click(screen.getByRole("button",{name:"BMI 계산하기"}));expect(screen.getAllByRole("alert").length).toBeGreaterThanOrEqual(3);});
});
