"use client";
import {useState} from "react";
import {FaqAccordion} from "@/components/calculator/FaqAccordion";
import {SectionCard} from "@/components/calculator/SectionCard";
import {ShareActions} from "@/components/calculator/ShareActions";
import {asShareRecord,useCalculatorShare} from "@/components/calculator/useCalculatorShare";
import {buildStateShareUrl} from "@/src/lib/share";
import {completedMonths} from "./age";
import {bmiFaqItems} from "./content";
import {formatAge,formatNumber,formatPercentile} from "./formatting";
import {calculateBmi} from "./logic";
import type {BmiResult,Sex} from "./types";
import {validateBmiInput,type RawBmiInput} from "./validation";

function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
const initial:RawBmiInput={birthDate:"",referenceDate:today(),sex:"male",heightCm:"",weightKg:"",waistCm:""};
const fieldClass="mt-2 block w-full min-w-0 rounded-xl border border-border bg-background px-3.5 py-3 outline-none focus:border-primary focus:ring-4 focus:ring-primary/10";
function Icon({kind}:{kind:"info"|"chart"|"formula"}){return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8"><path d={kind==="info"?"M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-11v6m0-10h.01":kind==="chart"?"M4 19V9m6 10V5m6 14v-7m4 7H2":"M5 5h6l-4 7 4 7H5m10-9h5m-2.5-2.5v5"}/></svg>}

function selectedAgeGroup(form:RawBmiInput){if(!/^\d{4}-\d{2}-\d{2}$/.test(form.birthDate)||!/^\d{4}-\d{2}-\d{2}$/.test(form.referenceDate)||form.birthDate>form.referenceDate)return null;const months=completedMonths(form.birthDate,form.referenceDate);return months<24?"infant":months<228?"child":"adult";}
function AgeGuideCard({active,title,children}:{active:boolean;title:string;children:React.ReactNode}){return <div aria-current={active?"true":undefined} className={`rounded-xl border p-4 transition-colors ${active?"border-primary/40 bg-primary-soft ring-1 ring-primary/10":"border-transparent bg-surface-subtle"}`}><div className="flex items-center justify-between gap-2"><p className={`font-semibold ${active?"text-primary":""}`}>{title}</p>{active&&<span className="rounded-full bg-primary px-2 py-0.5 text-[11px] font-semibold text-primary-foreground">현재 적용</span>}</div><p className="mt-2 text-sm leading-6 text-muted">{children}</p></div>}
const adultRanges=[{label:"저체중",range:"18.5 미만",from:15,to:18.5},{label:"정상",range:"18.5~22.9",from:18.5,to:23},{label:"비만 전단계",range:"23~24.9",from:23,to:25},{label:"1단계 비만",range:"25~29.9",from:25,to:30},{label:"2단계 비만",range:"30~34.9",from:30,to:35},{label:"3단계 비만",range:"35 이상",from:35,to:40}] as const;
function AdultReference({bmi}:{bmi:number}){const marker=Math.max(1,Math.min(99,((bmi-15)/25)*100));return <SectionCard title="성인 BMI 기준표" description="현재 BMI가 전체 기준에서 어디에 위치하는지 보여줍니다." icon={<Icon kind="chart"/>}><div className="relative mt-7"><div className="flex h-3 overflow-hidden rounded-full">{adultRanges.map((item,index)=><span key={item.label} className={index===1?"bg-emerald-500":index<1?"bg-sky-400":index<3?"bg-amber-400":"bg-rose-400"} style={{width:`${(item.to-item.from)/25*100}%`}}/>)}</div><span className="absolute -top-5 -translate-x-1/2 text-xs font-bold text-primary" style={{left:`${marker}%`}}>▼ {formatNumber(bmi)}</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[34rem] text-left text-sm"><thead><tr className="border-b border-border text-muted"><th className="py-2 font-medium">구분</th><th className="py-2 font-medium">BMI 기준</th><th className="py-2 font-medium">현재 결과</th></tr></thead><tbody>{adultRanges.map((item,index)=>{const current=index===0?bmi<18.5:index===adultRanges.length-1?bmi>=35:bmi>=item.from&&bmi<item.to;return <tr key={item.label} className={`border-b border-border/70 last:border-0 ${current?"bg-primary-soft text-primary":""}`}><td className="px-2 py-2.5 font-semibold">{item.label}</td><td className="px-2 py-2.5 tabular-nums">{item.range}</td><td className="px-2 py-2.5 font-semibold">{current?"현재 위치":""}</td></tr>})}</tbody></table></div></SectionCard>}

export default function BmiCalculatorUi(){const[form,setForm]=useState(initial);const[errors,setErrors]=useState<Record<string,string>>({});const[result,setResult]=useState<BmiResult|null>(null);const activeAgeGroup=selectedAgeGroup(form);const baseUrl=useCalculatorShare((state)=>{const root=asShareRecord(state),saved=asShareRecord(root?.f);if(!saved)return;const candidate:RawBmiInput={birthDate:String(saved.birthDate??""),referenceDate:String(saved.referenceDate??""),sex:saved.sex==="female"?"female":"male",heightCm:String(saved.heightCm??""),weightKg:String(saved.weightKg??""),waistCm:String(saved.waistCm??"")};if(selectedAgeGroup(candidate)!=="adult")candidate.waistCm="";const checked=validateBmiInput(candidate);if(!checked.success)return;setForm(candidate);setErrors({});setResult(calculateBmi(checked.data));});
  function update(field:keyof RawBmiInput,value:string){setForm(previous=>{const next={...previous,[field]:value};if((field==="birthDate"||field==="referenceDate")&&selectedAgeGroup(next)!=="adult")next.waistCm="";return next});setResult(null);}
  function submit(e:React.FormEvent){e.preventDefault();const checked=validateBmiInput(form);if(!checked.success){setErrors(Object.fromEntries(checked.errors.map(x=>[x.field,x.message])));setResult(null);return}setErrors({});setResult(calculateBmi(checked.data));}
  return <div className="mx-auto w-full max-w-6xl flex-1 px-5 py-10 sm:px-8 sm:py-14">
    <header className="max-w-3xl"><p className="mb-3 text-sm font-semibold text-primary">건강</p><h1 className="text-3xl font-bold tracking-[-0.03em] sm:text-4xl">BMI 계산기</h1><p className="mt-3 text-base leading-7 text-muted">키와 체중으로 BMI를 계산하고, 기준일의 연령에 맞춰 성인은 고정 기준으로, 어린이·청소년은 성별·월령별 백분위수로 안내합니다.</p></header>
    <section className="mt-8 rounded-2xl border border-border bg-surface p-5 sm:p-7"><h2 className="text-lg font-bold">연령에 따라 이렇게 구분해요</h2>{!activeAgeGroup&&<p className="mt-2 text-sm text-muted">생년월일을 입력하면 적용되는 기준이 강조됩니다.</p>}<div className="mt-4 grid gap-3 md:grid-cols-3"><AgeGuideCard active={activeAgeGroup==="infant"} title="만 2세 미만">BMI 수치만 계산하고 비만도는 판정하지 않습니다. 영유아는 신장별 체중과 성장 흐름을 함께 살펴야 합니다.</AgeGuideCard><AgeGuideCard active={activeAgeGroup==="child"} title="만 2세 이상 ~ 만 19세 미만">같은 성별과 나이의 또래 100명 중 BMI가 어느 위치인지 비교합니다. 5·85·95번째 위치가 구분점입니다.</AgeGuideCard><AgeGuideCard active={activeAgeGroup==="adult"} title="만 19세 이상">대한비만학회의 한국 성인 기준을 적용합니다. BMI 23부터 비만 전단계, 25부터 비만으로 분류합니다.</AgeGuideCard></div><div className="mt-4 rounded-xl border-l-4 border-primary bg-background px-4 py-3"><p className="text-sm font-semibold">왜 어린이·청소년은 성인 기준과 다를까요?</p><p className="mt-1 text-sm leading-6 text-muted">성장기에는 키·체중과 체지방 분포가 계속 바뀌고 사춘기 변화도 성별마다 다릅니다. 같은 BMI라도 나이와 성별에 따라 의미가 달라, 고정 숫자 대신 같은 성별·나이의 또래 분포와 비교합니다.</p></div></section>
    <form onSubmit={submit} noValidate className="mt-6 space-y-6 rounded-2xl border border-border bg-surface p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">생년월일 <span className="text-danger">*</span><input type="date" value={form.birthDate} onChange={e=>update("birthDate",e.target.value)} className={fieldClass}/>{errors.birthDate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.birthDate}</span>}</label><label className="text-sm font-semibold">측정 기준일 <span className="text-danger">*</span><input type="date" value={form.referenceDate} onChange={e=>update("referenceDate",e.target.value)} className={fieldClass}/>{errors.referenceDate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.referenceDate}</span>}</label></div>
      <fieldset><legend className="text-sm font-semibold">성별 <span className="text-danger">*</span></legend><p className="mt-1 text-xs leading-5 text-muted">소아청소년의 또래 비교와 성인 허리둘레 기준에 사용합니다.</p><div className="mt-3 grid max-w-md grid-cols-2 gap-2">{([['male','남성'],['female','여성']] as [Sex,string][]).map(([value,label])=><label key={value} className={`cursor-pointer rounded-xl border px-4 py-3 text-center text-sm font-semibold ${form.sex===value?'border-primary bg-primary-soft text-primary':'border-border bg-background'}`}><input className="sr-only" type="radio" name="sex" checked={form.sex===value} onChange={()=>update("sex",value)}/>{label}</label>)}</div></fieldset>
      <div className={`grid gap-5 ${activeAgeGroup==="adult"?"sm:grid-cols-3":"sm:grid-cols-2"}`}>{([['heightCm','키','cm'],['weightKg','체중','kg']] as const).map(([field,label,unit])=><label key={field} className="text-sm font-semibold">{label} <span className="text-danger">*</span><div className="relative"><input inputMode="decimal" value={form[field]} onChange={e=>update(field,e.target.value)} className={`${fieldClass} pr-12`}/><span className="absolute right-4 top-1/2 mt-1 -translate-y-1/2 text-sm text-muted">{unit}</span></div>{errors[field]&&<span role="alert" className="mt-1 block font-normal text-danger">{errors[field]}</span>}</label>)}{activeAgeGroup==="adult"&&<label className="text-sm font-semibold">허리둘레 <span className="font-normal text-muted">(선택)</span><div className="relative"><input inputMode="decimal" value={form.waistCm} onChange={e=>update("waistCm",e.target.value)} className={`${fieldClass} pr-12`}/><span className="absolute right-4 top-1/2 mt-1 -translate-y-1/2 text-sm text-muted">cm</span></div><span className="mt-1.5 block font-normal text-muted">성인의 복부비만 기준을 함께 확인합니다.</span>{errors.waistCm&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.waistCm}</span>}</label>}</div>
      {activeAgeGroup!=="adult"&&<p className="-mt-3 text-xs leading-5 text-muted">허리둘레 입력은 만 19세 이상 성인에게만 표시됩니다.</p>}
      <div className="flex flex-wrap gap-3"><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">BMI 계산하기</button><button type="button" onClick={()=>{setForm({...initial,birthDate:"2014-09-16",heightCm:"150",weightKg:"45"});setResult(null);setErrors({});}} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold">소아 예시</button><button type="button" onClick={()=>{setForm(initial);setResult(null);setErrors({});}} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold text-muted">초기화</button></div>
    </form>
    <ShareActions className="mt-5" title="BMI 계산기" text={result?`BMI ${formatNumber(result.bmi)} · ${result.category}입니다.`:"연령에 맞는 기준으로 BMI를 확인해 보세요."} url={baseUrl?(result?buildStateShareUrl(baseUrl,{f:form}):baseUrl):undefined} mode={result?"result":"calculator"}/>
    <div aria-live="polite" className="mt-8 space-y-5">{result&&<><section className="rounded-2xl border border-transparent bg-primary p-6 text-primary-foreground shadow-[0_20px_60px_-30px_rgba(49,87,213,.8)] dark:border-primary/25 dark:bg-gradient-to-br dark:from-primary-soft dark:via-surface dark:to-surface dark:text-foreground sm:p-8"><p className="text-sm font-semibold opacity-80 dark:text-muted">{formatAge(result.ageYears,result.ageMonths)} 기준</p><div className="mt-2 flex flex-wrap items-end gap-x-5 gap-y-2"><p className="text-5xl font-bold tabular-nums dark:text-primary">{formatNumber(result.bmi)}</p><p className="pb-1 text-xl font-bold">{result.category}</p></div>{result.percentile!==undefined&&<div className="mt-4"><p className="text-base font-semibold">같은 성별·나이 또래 100명 중 낮은 쪽부터 약 {Math.round(result.percentile)}번째</p><p className="mt-1 text-xs opacity-80 dark:text-muted">키 순서가 아니라 BMI가 낮은 순서로 비교한 위치이며, 점수나 건강 순위가 아닙니다.</p></div>}{result.ageGroup==="infant"&&<p className="mt-4 text-sm">만 2세 미만은 공식 연령별 BMI 분류 대상이 아니므로 수치만 제공합니다.</p>}</section>
      {result.ageGroup==="adult"&&<AdultReference bmi={result.bmi}/>} 
      <SectionCard title="계산 상세" icon={<Icon kind="chart"/>}><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted">키</dt><dd className="mt-1 font-semibold">{formatNumber(result.heightCm)}cm</dd></div><div><dt className="text-muted">체중</dt><dd className="mt-1 font-semibold">{formatNumber(result.weightKg)}kg</dd></div><div><dt className="text-muted">적용 기준</dt><dd className="mt-1 font-semibold">{result.ageGroup==="child"?`2017 성장도표 · ${result.ageMonths}개월`:result.ageGroup==="adult"?"한국 성인 BMI":"수치만 계산"}</dd></div>{result.waistCm!==undefined&&<div><dt className="text-muted">복부비만 기준</dt><dd className="mt-1 font-semibold">{result.waistRisk?"기준 이상":"기준 미만"} ({formatNumber(result.waistCm)}cm)</dd></div>}</dl>{result.childBmiCuts&&<div className="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-surface-subtle p-3 text-center text-xs"><div><span className="text-muted">5백분위</span><strong className="mt-1 block">BMI {formatNumber(result.childBmiCuts.p5)}</strong></div><div><span className="text-muted">85백분위</span><strong className="mt-1 block">BMI {formatNumber(result.childBmiCuts.p85)}</strong></div><div><span className="text-muted">95백분위</span><strong className="mt-1 block">BMI {formatNumber(result.childBmiCuts.p95)}</strong></div></div>}{result.healthyWeightMin!==undefined&&<p className="mt-4 rounded-xl bg-surface-subtle p-3 text-sm">현재 키에서 {result.ageGroup==="child"?"5백분위 이상 85백분위 미만":"BMI 18.5 이상 23 미만"}에 대응하는 참고 체중은 약 <strong>{formatNumber(result.healthyWeightMin)}~{formatNumber(result.healthyWeightMax!)}kg</strong>입니다. {result.ageGroup==="child"&&"목표 체중이나 감량 권고가 아닙니다."}</p>}</SectionCard>
      <SectionCard title="계산 방법" icon={<Icon kind="formula"/>}><ol className="space-y-3 text-sm leading-6"><li><strong>1. BMI 계산</strong><p className="text-muted">{formatNumber(result.weightKg)}kg ÷ ({formatNumber(result.heightCm/100,2)}m × {formatNumber(result.heightCm/100,2)}m) = {formatNumber(result.bmi)}</p></li><li><strong>2. 연령 기준 선택</strong><p className="text-muted">기준일에 {result.ageMonths}개월이므로 {result.ageGroup==="child"?"같은 성별·나이의 또래와 비교하는 성장도표 기준을":result.ageGroup==="adult"?"성인 고정 구간 기준을":"별도 비만도 기준 없이 BMI 수치만"} 적용했습니다.</p></li>{result.percentile!==undefined&&<li><strong>3. 또래 위치 판정</strong><p className="text-muted">또래 분포에서 낮은 쪽부터 5번째 미만은 저체중, 5~84번째는 정상, 85~94번째는 과체중, 95번째 이상은 비만으로 안내합니다.</p><details className="mt-2 rounded-lg bg-surface-subtle px-3 py-2"><summary className="cursor-pointer font-medium">통계 상세 보기</summary><p className="mt-2 text-muted">정확한 계산값은 {formatPercentile(result.percentile)}백분위수, Z점수 {formatNumber(result.zScore!,2)}입니다. 백분위수는 또래 분포상의 위치이고, Z점수는 평균에서 얼마나 떨어져 있는지를 통계 단위로 표현한 내부 계산값입니다.</p></details></li>}</ol></SectionCard>
      <SectionCard title="꼭 확인하세요" icon={<Icon kind="info"/>}><p className="text-sm leading-6 text-muted">BMI와 백분위수는 선별을 위한 참고 지표이며 진단이 아닙니다. 근육량, 체지방 분포, 성장 속도와 질환은 반영하지 않으므로 결과가 걱정되면 의료진과 상담하세요.</p></SectionCard></>}</div>
    <section className="mt-10 rounded-2xl bg-surface-subtle p-6 text-sm leading-7 text-muted">소아청소년 결과는 질병관리청·대한소아청소년과학회의 2017 소아청소년 성장도표(24~227개월), 성인 결과는 대한비만학회 한국인 기준을 사용합니다. 입력값은 저장하거나 서버로 전송하지 않습니다.</section><div className="mt-5"><FaqAccordion items={bmiFaqItems.map(x=>({...x,answer:[...x.answer]}))}/></div>
  </div>}
