import {addDays,addMonths,completedServiceMonths} from "./date-utils";
import {rankPay,servicePolicies,standardRankMonths} from "./policy";
import type {MilitaryRank,MilitarySalaryInput,MilitarySalaryResult,RankSalarySegment} from "./types";
import {calculateInstallmentSimpleInterestTotal} from "@/src/lib/installment-savings";
const ranks:MilitaryRank[]=["private-2","private-1","corporal","sergeant"];
function customRankMonths(input:MilitarySalaryInput,total:number){if(!input.promotionDates)return standardRankMonths(total);const p=input.promotionDates;const a=Math.min(total,completedServiceMonths(input.enlistmentDate,p.private1));const b=Math.min(total,completedServiceMonths(input.enlistmentDate,p.corporal));const c=Math.min(total,completedServiceMonths(input.enlistmentDate,p.sergeant));return{"private-2":a,"private-1":Math.max(0,b-a),corporal:Math.max(0,c-b),sergeant:Math.max(0,total-c)};}
function trimSegments(monthsByRank:Record<MilitaryRank,number>,limit:number):RankSalarySegment[]{let remaining=limit;return ranks.map(rank=>{const months=Math.min(monthsByRank[rank],remaining);remaining-=months;return{rank,months,monthlyPayWon:rankPay[rank],subtotalWon:months*rankPay[rank]};}).filter(x=>x.months>0);}
export function calculateMilitarySalary(input:MilitarySalaryInput):MilitarySalaryResult{const serviceMonths=servicePolicies[input.serviceType].months;const calculatedMonths=input.mode==="full-service"?serviceMonths:Math.min(serviceMonths,completedServiceMonths(input.enlistmentDate,input.referenceDate!));const segments=trimSegments(customRankMonths(input,serviceMonths),calculatedMonths);const grossSalaryWon=segments.reduce((sum,x)=>sum+x.subtotalWon,0);let savingsResult;
 if(input.savings.enabled){const s=input.savings,principalWon=s.monthlyContributionWon*s.contributionMonths;const estimatedInterestWon=calculateInstallmentSimpleInterestTotal(s.monthlyContributionWon,s.expectedAnnualRatePercent,s.contributionMonths);const matchingSupportWon=principalWon;savingsResult={principalWon,estimatedInterestWon,matchingSupportWon,estimatedMaturityWon:principalWon+estimatedInterestWon+matchingSupportWon};}
 const paidSavingsToScope=input.savings.enabled?input.savings.monthlyContributionWon*Math.min(input.savings.contributionMonths,calculatedMonths):0;
 return{...input,serviceMonths,calculatedMonths,estimatedDischargeDate:addDays(addMonths(input.enlistmentDate,serviceMonths),-1),segments,grossSalaryWon,availableDuringServiceWon:grossSalaryWon-paidSavingsToScope,savingsResult};}
