import {describe,expect,it} from "vitest";import {calculateMilitarySalary} from "./logic";import type {MilitarySalaryInput} from "./types";
const base:MilitarySalaryInput={serviceType:"army",enlistmentDate:"2026-01-01",mode:"full-service",savings:{enabled:false,monthlyContributionWon:0,contributionMonths:0,expectedAnnualRatePercent:0}};
describe("군인 월급 계산",()=>{it("육군 18개월 계급별 봉급을 합산한다",()=>{const r=calculateMilitarySalary(base);expect(r.segments.map(x=>x.months)).toEqual([2,6,6,4]);expect(r.grossSalaryWon).toBe(20100000);expect(r.estimatedDischargeDate).toBe("2027-06-30")});it("해군과 공군의 병장 기간을 반영한다",()=>{expect(calculateMilitarySalary({...base,serviceType:"navy"}).grossSalaryWon).toBe(23100000);expect(calculateMilitarySalary({...base,serviceType:"air-force"}).grossSalaryWon).toBe(24600000)});it("기준일까지 완성된 복무개월만 계산한다",()=>{const r=calculateMilitarySalary({...base,mode:"to-reference-date",referenceDate:"2026-09-01"});expect(r.calculatedMonths).toBe(8);expect(r.grossSalaryWon).toBe(6900000)});it("원금·이자·100% 매칭을 분리한다",()=>{const r=calculateMilitarySalary({...base,savings:{enabled:true,monthlyContributionWon:550000,contributionMonths:18,expectedAnnualRatePercent:5}});expect(r.savingsResult).toEqual({principalWon:9900000,estimatedInterestWon:391875,matchingSupportWon:9900000,estimatedMaturityWon:20191875});expect(r.availableDuringServiceWon).toBe(10200000)});it("기준일까지 사용 가능액에서는 해당 시점까지 납입한 원금만 뺀다",()=>{const r=calculateMilitarySalary({...base,mode:"to-reference-date",referenceDate:"2026-09-01",savings:{enabled:true,monthlyContributionWon:550000,contributionMonths:18,expectedAnnualRatePercent:5}});expect(r.availableDuringServiceWon).toBe(6900000-550000*8)});it("실제 진급일을 적용한다",()=>{const r=calculateMilitarySalary({...base,promotionDates:{private1:"2026-04-01",corporal:"2026-10-01",sergeant:"2027-03-01"}});expect(r.segments.map(x=>x.months)).toEqual([3,6,5,4])});
// Calculation Auditor 재검증(tasks/deposit-savings-interest-calculator/EVALUATION.md
// "## Calculation Auditor (재검증)" "3-B" 절)이 이 계산기가 그대로 import해서 쓰는 공유
// 함수 calculateInstallmentSimpleInterestTotal(src/lib/installment-savings.ts)에서 부동
// 소수점 오차로 인한 High 결함(epsilon 보정이 전혀 없어 전체 입력 도메인의 5~10%가 정확히
// 1원 작게 계산됨)을 발견했다 — 이미 배포된 이 계산기에도 실제로 영향을 준 결함이었다.
// 아래는 그 반례를 이 계산기 관점에서도 회귀 방지용 Golden Test로 고정한다(공유 함수 자체의
// 광범위한 검증은 src/lib/installment-savings.test.ts 참고). 수정 전 구현에서는
// estimatedInterestWon=11,054(오답)가 나왔고, 수정 후에는 정답 11,055가 나온다.
it("공유 함수(installment-savings)의 부동소수점 버그 수정 회귀 테스트 — 550,000원·연4.02%·3개월 적금 이자는 11,055원(수정 전 오답 11,054원)",()=>{const r=calculateMilitarySalary({...base,savings:{enabled:true,monthlyContributionWon:550000,contributionMonths:3,expectedAnnualRatePercent:4.02}});expect(r.savingsResult).toEqual({principalWon:1650000,estimatedInterestWon:11055,matchingSupportWon:1650000,estimatedMaturityWon:3311055})});});
