"use client";
import Link from "next/link";
import {useState} from "react";
import {FaqAccordion} from "@/components/calculator/FaqAccordion";
import {SectionCard} from "@/components/calculator/SectionCard";
import {ShareActions} from "@/components/calculator/ShareActions";
import {asShareRecord,useCalculatorShare} from "@/components/calculator/useCalculatorShare";
import {buildStateShareUrl} from "@/src/lib/share";
import { kakaoShareAdapter } from "@/src/lib/kakao-share";
import {militarySalaryFaqItems} from "./content";
import {addMonths,isIsoDate} from "./date-utils";
import {koreanDate,won} from "./formatting";
import {calculateMilitarySalary} from "./logic";
import {MILITARY_POLICY_REVIEWED_AT,MILITARY_POLICY_YEAR,rankLabels,servicePolicies} from "./policy";
import type {MilitarySalaryResult,MilitaryServiceType} from "./types";
import {validateMilitarySalary,type RawMilitarySalaryInput} from "./validation";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const initial:RawMilitarySalaryInput={serviceType:"army",enlistmentDate:"",mode:"full-service",referenceDate:today(),useActualPromotions:false,private1Date:"",corporalDate:"",sergeantDate:"",savingsEnabled:false,monthlyContribution:"550000",contributionMonths:"18",annualRate:"5"};
const field="mt-2 block w-full min-w-0 rounded-xl border border-border bg-background px-3.5 py-3 outline-none focus:border-primary focus:ring-4 focus:ring-primary/10";
function Icon({kind}:{kind:"money"|"list"|"formula"|"info"}){const d={money:"M12 2v20m5-16H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H7",list:"M8 6h12M8 12h12M8 18h12M4 6h.01M4 12h.01M4 18h.01",formula:"M5 5h6l-4 7 4 7H5m10-9h5m-2.5-2.5v5",info:"M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-11v6m0-10h.01"};return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={d[kind]}/></svg>}
function standardDates(enlistmentDate:string){if(!isIsoDate(enlistmentDate))return{private1Date:"",corporalDate:"",sergeantDate:""};return{private1Date:addMonths(enlistmentDate,2),corporalDate:addMonths(enlistmentDate,8),sergeantDate:addMonths(enlistmentDate,14)}}

export default function MilitarySalaryUi(){const[form,setForm]=useState(initial);const[errors,setErrors]=useState<Record<string,string>>({});const[result,setResult]=useState<MilitarySalaryResult|null>(null);const policy=servicePolicies[form.serviceType];const baseUrl=useCalculatorShare(state=>{const root=asShareRecord(state),saved=asShareRecord(root?.f);if(!saved)return;const candidate={...initial,...saved} as RawMilitarySalaryInput;if(!(candidate.serviceType in servicePolicies)||typeof candidate.enlistmentDate!=="string")return;const checked=validateMilitarySalary(candidate);if(!checked.success)return;setForm(candidate);setErrors({});setResult(calculateMilitarySalary(checked.data));});
 function update<K extends keyof RawMilitarySalaryInput>(key:K,value:RawMilitarySalaryInput[K]){setForm(previous=>{const next={...previous,[key]:value};if(key==="serviceType"){const months=servicePolicies[value as MilitaryServiceType].months;next.contributionMonths=String(Math.min(Number(next.contributionMonths)||months,months));}if(key==="enlistmentDate"&&next.useActualPromotions)Object.assign(next,standardDates(String(value)));return next});setResult(null);}
 function submit(e:React.FormEvent){e.preventDefault();const checked=validateMilitarySalary(form);if(!checked.success){setErrors(Object.fromEntries(checked.errors.map(x=>[x.field,x.message])));setResult(null);return}setErrors({});setResult(calculateMilitarySalary(checked.data));}
 function sample(){setForm({...initial,enlistmentDate:"2026-09-04",savingsEnabled:true});setErrors({});setResult(null);}
 return <div className="mx-auto w-full max-w-6xl flex-1 px-5 py-10 sm:px-8 sm:py-14"><header className="max-w-3xl"><Link href="/categories/finance" className="mb-3 inline-block text-sm font-semibold text-primary hover:underline">금융</Link><h1 className="text-3xl font-bold tracking-[-0.03em] sm:text-4xl">군인 월급 계산기</h1><p className="mt-3 text-base leading-7 text-muted">복무형태와 입영일로 계급별 예상 봉급을 계산하고, 장병내일준비적금 가입 시 본인 납입금과 전역 후 예상 만기자산을 따로 보여드립니다.</p><p className="mt-2 text-sm font-semibold text-primary">{MILITARY_POLICY_YEAR}년 병 봉급 기준 · {MILITARY_POLICY_REVIEWED_AT} 검토</p></header>
  <section className="mt-8 rounded-2xl border border-border bg-surface p-5 sm:p-7"><h2 className="text-lg font-bold">월급과 군적금은 따로 계산해요</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-surface-subtle p-4"><p className="font-semibold">봉급</p><p className="mt-2 text-sm leading-6 text-muted">계급별로 매월 지급되는 금액입니다.</p></div><div className="rounded-xl bg-surface-subtle p-4"><p className="font-semibold">본인 납입금</p><p className="mt-2 text-sm leading-6 text-muted">월급에서 적금 계좌로 저축하는 본인의 돈입니다.</p></div><div className="rounded-xl bg-primary-soft p-4"><p className="font-semibold text-primary">정부 매칭지원금</p><p className="mt-2 text-sm leading-6 text-muted">매월 현금으로 받는 월급이 아니라 적격 만기해지 후 받는 지원금입니다.</p></div></div></section>
  <form onSubmit={submit} noValidate className="mt-6 space-y-7 rounded-2xl border border-border bg-surface p-5 sm:p-8"><fieldset><legend className="text-sm font-semibold">복무형태</legend><div className="mt-3 grid gap-2 sm:grid-cols-3 lg:grid-cols-5">{(Object.entries(servicePolicies) as [MilitaryServiceType,{label:string;months:number}][]).map(([value,item])=><label key={value} className={`cursor-pointer rounded-xl border px-3 py-3 text-center text-sm font-semibold ${form.serviceType===value?"border-primary bg-primary-soft text-primary":"border-border bg-background"}`}><input className="sr-only" type="radio" name="serviceType" checked={form.serviceType===value} onChange={()=>update("serviceType",value)}/>{item.label}<span className="mt-1 block text-xs font-normal text-muted">{item.months}개월</span></label>)}</div></fieldset>
   <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">입영일 <span className="text-danger">*</span><input type="date" value={form.enlistmentDate} onChange={e=>update("enlistmentDate",e.target.value)} className={field}/>{errors.enlistmentDate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.enlistmentDate}</span>}</label><fieldset><legend className="text-sm font-semibold">계산 범위</legend><div className="mt-2 grid grid-cols-2 gap-2">{([['full-service','전체 복무'],['to-reference-date','기준일까지']] as const).map(([value,label])=><label key={value} className={`cursor-pointer rounded-xl border px-3 py-3 text-center text-sm font-semibold ${form.mode===value?"border-primary bg-primary-soft text-primary":"border-border bg-background"}`}><input className="sr-only" type="radio" name="mode" checked={form.mode===value} onChange={()=>update("mode",value)}/>{label}</label>)}</div></fieldset></div>{form.mode==="to-reference-date"&&<label className="block max-w-md text-sm font-semibold">계산 기준일 <span className="text-danger">*</span><input type="date" value={form.referenceDate} onChange={e=>update("referenceDate",e.target.value)} className={field}/>{errors.referenceDate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.referenceDate}</span>}</label>}
   <details className="rounded-xl border border-border bg-background p-4"><summary className="cursor-pointer text-sm font-semibold">실제 진급일 고급 설정</summary><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.useActualPromotions} onChange={e=>{const enabled=e.target.checked;setForm(p=>({...p,useActualPromotions:enabled,...(enabled?standardDates(p.enlistmentDate):{})}));setResult(null)}} className="h-4 w-4 accent-primary"/>실제 진급일로 계산</label>{form.useActualPromotions&&<div className="mt-4 grid gap-4 sm:grid-cols-3">{([['private1Date','일병 진급일'],['corporalDate','상병 진급일'],['sergeantDate','병장 진급일']] as const).map(([key,label])=><label key={key} className="text-sm font-semibold">{label}<input type="date" value={form[key]} onChange={e=>update(key,e.target.value)} className={field}/>{errors[key]&&<span role="alert" className="mt-1 block font-normal text-danger">{errors[key]}</span>}</label>)}</div>}<p className="mt-3 text-xs leading-5 text-muted">기본값은 이병 2개월·일병 6개월·상병 6개월의 진급 최저복무기간입니다. 실제 발령은 달라질 수 있습니다.</p></details>
   <fieldset className="border-t border-border pt-6"><legend className="text-sm font-semibold">장병내일준비적금</legend><div className="mt-3 grid max-w-md grid-cols-2 gap-2">{[[false,'가입 안 함'],[true,'가입']] .map(([value,label])=><label key={String(value)} className={`cursor-pointer rounded-xl border px-3 py-3 text-center text-sm font-semibold ${form.savingsEnabled===value?"border-primary bg-primary-soft text-primary":"border-border bg-background"}`}><input className="sr-only" type="radio" name="savings" checked={form.savingsEnabled===value} onChange={()=>update("savingsEnabled",value as boolean)}/>{label as string}</label>)}</div>{form.savingsEnabled&&<div className="mt-5 grid gap-5 sm:grid-cols-3"><label className="text-sm font-semibold">월 납입액<select value={form.monthlyContribution} onChange={e=>update("monthlyContribution",e.target.value)} className={field}>{Array.from({length:11},(_,i)=>(i+1)*50000).map(value=><option key={value} value={value}>{won(value)}</option>)}</select>{errors.monthlyContribution&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.monthlyContribution}</span>}</label><label className="text-sm font-semibold">납입 개월<input inputMode="numeric" value={form.contributionMonths} onChange={e=>update("contributionMonths",e.target.value.replace(/\D/g,""))} className={field}/><span className="mt-1 block font-normal text-muted">6~{policy.months}개월</span>{errors.contributionMonths&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.contributionMonths}</span>}</label><label className="text-sm font-semibold">예상 연 금리<input inputMode="decimal" value={form.annualRate} onChange={e=>update("annualRate",e.target.value)} className={field}/><span className="mt-1 block font-normal text-muted">은행이자 추정용, 기본 5%</span>{errors.annualRate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.annualRate}</span>}</label></div>}</fieldset>
   <div className="flex flex-wrap gap-3"><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">예상 월급 계산하기</button><button type="button" onClick={sample} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold">육군·군적금 예시</button><button type="button" onClick={()=>{setForm(initial);setErrors({});setResult(null)}} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold text-muted">초기화</button></div>
  </form>
  <ShareActions className="mt-5" title="군인 월급 계산기" text={result?`${servicePolicies[result.serviceType].label} 예상 봉급은 ${won(result.grossSalaryWon)}입니다.`:"복무형태별 병 봉급과 군적금 만기자산을 계산해 보세요."} url={baseUrl?(result?buildStateShareUrl(baseUrl,{f:form}):baseUrl):undefined} mode={result?"result":"calculator"} onKakaoShare={kakaoShareAdapter}/>
  <div aria-live="polite" className="mt-8 space-y-5">{result&&<><section className="rounded-2xl border border-transparent bg-primary p-6 text-primary-foreground shadow-[0_20px_60px_-30px_rgba(49,87,213,.8)] dark:border-primary/25 dark:bg-gradient-to-br dark:from-primary-soft dark:via-surface dark:to-surface dark:text-foreground sm:p-8"><p className="text-sm font-semibold opacity-80 dark:text-muted">{servicePolicies[result.serviceType].label} · {result.mode==="full-service"?`전체 ${result.serviceMonths}개월`:`기준일까지 ${result.calculatedMonths}개월`}</p><p className="mt-2 text-4xl font-bold tracking-[-0.04em] tabular-nums dark:text-primary sm:text-5xl">{won(result.grossSalaryWon)}</p><p className="mt-4 text-sm">예상 봉급 합계 · 예상 전역일 {koreanDate(result.estimatedDischargeDate)}</p></section>
   <SectionCard title="계급별 봉급 내역" icon={<Icon kind="list"/>}><div className="overflow-x-auto"><table className="w-full min-w-[34rem] text-left text-sm"><thead><tr className="border-b border-border text-muted"><th className="py-2">계급</th><th className="py-2">계산 개월</th><th className="py-2">월 봉급</th><th className="py-2 text-right">소계</th></tr></thead><tbody>{result.segments.map(x=><tr key={x.rank} className="border-b border-border/70"><td className="py-3 font-semibold">{rankLabels[x.rank]}</td><td className="py-3">{x.months}개월</td><td className="py-3">{won(x.monthlyPayWon)}</td><td className="py-3 text-right font-semibold">{won(x.subtotalWon)}</td></tr>)}</tbody><tfoot><tr><th colSpan={3} className="py-3">봉급 합계</th><th className="py-3 text-right text-primary">{won(result.grossSalaryWon)}</th></tr></tfoot></table></div></SectionCard>
   {result.savingsResult&&<SectionCard title="군적금 예상 내역" description="봉급과 별도로 전역 후 받을 수 있는 예상 만기자산입니다." icon={<Icon kind="money"/>}><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted">본인 납입원금</dt><dd className="mt-1 font-semibold">{won(result.savingsResult.principalWon)}</dd></div><div><dt className="text-muted">예상 은행이자</dt><dd className="mt-1 font-semibold">{won(result.savingsResult.estimatedInterestWon)}</dd></div><div><dt className="text-muted">정부 매칭지원금</dt><dd className="mt-1 font-semibold text-primary">{won(result.savingsResult.matchingSupportWon)}</dd></div><div><dt className="text-muted">예상 만기자산</dt><dd className="mt-1 text-lg font-bold">{won(result.savingsResult.estimatedMaturityWon)}</dd></div></dl><p className="mt-4 rounded-xl bg-surface-subtle p-3 text-sm">봉급 중 적금 납입원금을 제외한 복무 중 사용 가능 예상액은 <strong>{won(result.availableDuringServiceWon)}</strong>입니다.</p><p className="mt-3 text-xs leading-5 text-muted">은행이자는 입력 금리로 추정한 값이며, 정부지원금은 전역·소집해제 후 적격 만기해지 요건을 충족해야 지급됩니다.</p></SectionCard>}
   <SectionCard title="계산 방법" icon={<Icon kind="formula"/>}><ol className="space-y-3 text-sm leading-6"><li><strong>1. 계급별 봉급</strong><p className="text-muted">각 계급의 계산 개월 × 2026년 월 봉급을 합산했습니다.</p></li><li><strong>2. 계급 일정</strong><p className="text-muted">{result.promotionDates?"입력한 실제 진급일을 복무개월 경계로 환산했습니다.":"이병 2개월, 일병 6개월, 상병 6개월 뒤 진급하는 표준 예상 일정을 적용했습니다."}</p></li>{result.savingsResult&&<li><strong>3. 군적금</strong><p className="text-muted">원금 {won(result.savingsResult.principalWon)} + 예상이자 {won(result.savingsResult.estimatedInterestWon)} + 원금 100% 매칭 {won(result.savingsResult.matchingSupportWon)} = {won(result.savingsResult.estimatedMaturityWon)}</p></li>}</ol></SectionCard>
   <SectionCard title="계산 전 확인" icon={<Icon kind="info"/>}><p className="text-sm leading-6 text-muted">계급별 월 봉급에 표준 복무개월을 곱한 계획용 추정입니다. 월중 입영·진급·전역의 일할 지급, 진급 제한·연기, 수당과 개인 공제는 반영하지 않으며 실제 급여명세와 금융기관의 지급 결과가 우선합니다.</p></SectionCard></>}</div>
  <section className="mt-10 rounded-2xl bg-surface-subtle p-6 text-sm leading-7 text-muted">2026년 공무원보수규정 별표 13과 국방부 장병내일준비적금 안내를 기준으로 합니다. 사회복무요원과 간부 급여는 계산하지 않습니다. 입력값은 저장하거나 서버로 전송하지 않습니다.</section><div className="mt-5"><FaqAccordion items={militarySalaryFaqItems.map(x=>({...x,answer:[...x.answer]}))}/></div></div>}
