"use client";

import { useMemo, useState } from "react";
import { FaqAccordion } from "@/components/calculator/FaqAccordion";
import { SectionCard } from "@/components/calculator/SectionCard";
import { ShareActions } from "@/components/calculator/ShareActions";
import { asShareRecord, useCalculatorShare } from "@/components/calculator/useCalculatorShare";
import { buildStateShareUrl } from "@/src/lib/share";
import { parentalLeaveBenefitFaqItems } from "./content";
import { formatKoreanDate, formatShortDate, formatWon } from "./formatting";
import { calculateParentalLeaveBenefit } from "./logic";
import { PARENTAL_LEAVE_POLICY_NEXT_REVIEW, PARENTAL_LEAVE_POLICY_REVIEWED_AT } from "./policy";
import type { BenefitScheme, ParentalLeaveBenefitInput, ParentalLeaveBenefitResult } from "./types";
import { validateParentalLeaveBenefitInput, type RawParentalLeaveBenefitInput } from "./validation";

const schemeLabels: Record<BenefitScheme, string> = { general: "일반", "parents-together": "부모 함께", "single-parent": "한부모 특례" };
const fieldClass = "mt-2 block min-w-0 w-full rounded-xl border border-border bg-background px-3.5 py-3 outline-none focus:border-primary focus:ring-4 focus:ring-primary/10";
function Icon({ name }: { name: "result" | "detail" | "formula" | "info" }) {
  const paths = { result: <path d="M4 19V9m6 10V5m6 14v-7m4 7H2" />, detail: <path d="M6 3h9l3 3v15H6zM9 11h6m-6 4h6" />, formula: <path d="M5 5h6L7 12l4 7H5m10-9h5m-2.5-2.5v5" />, info: <path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-11v6m0-10h.01" /> };
  return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}

const initial: RawParentalLeaveBenefitInput = { startDate: "", leaveMonths: "12", ordinaryWageWon: "", scheme: "general", priorLeaveMonths: "0", childBirthDate: "", spouseStartDate: "", spouseLeaveMonths: "6", spouseLeaveStatus: "used", extensionEligibility: "" };

export default function ParentalLeaveBenefitUi() {
  const [form, setForm] = useState(initial);
  const [errors, setErrors] = useState<Record<string,string>>({});
  const [result, setResult] = useState<ParentalLeaveBenefitResult | null>(null);
  const [applied, setApplied] = useState<ParentalLeaveBenefitInput | null>(null);
  const baseUrl = useCalculatorShare((state) => {
    const root = asShareRecord(state); const saved = asShareRecord(root?.f);
    const keys = ["startDate","leaveMonths","ordinaryWageWon","scheme","priorLeaveMonths","childBirthDate","spouseStartDate","spouseLeaveMonths","spouseLeaveStatus","extensionEligibility"];
    if (!saved || !keys.every((key) => typeof saved[key] === "string")) return;
    const restored = saved as unknown as RawParentalLeaveBenefitInput;
    const checked = validateParentalLeaveBenefitInput(restored); if (!checked.success) return;
    setForm(restored); setErrors({}); setApplied(checked.data); setResult(calculateParentalLeaveBenefit(checked.data));
  });
  const totalMonths = (Number(form.leaveMonths) || 0) + (Number(form.priorLeaveMonths) || 0);
  const estimatedEnd = useMemo(() => {
    const checked = validateParentalLeaveBenefitInput({ ...form, ordinaryWageWon: form.ordinaryWageWon || "1", extensionEligibility: totalMonths > 12 ? "both-parents" : form.extensionEligibility });
    if (!checked.success) return "";
    return calculateParentalLeaveBenefit(checked.data).endDate;
  }, [form, totalMonths]);
  function update<K extends keyof RawParentalLeaveBenefitInput>(key: K, value: RawParentalLeaveBenefitInput[K]) { setForm((prev) => ({ ...prev, [key]: value })); setResult(null); setApplied(null); }
  function submit(event: React.FormEvent) {
    event.preventDefault(); const checked = validateParentalLeaveBenefitInput(form);
    if (!checked.success) { setErrors(Object.fromEntries(checked.errors.map((e) => [e.field,e.message]))); setResult(null); return; }
    setErrors({}); setApplied(checked.data); setResult(calculateParentalLeaveBenefit(checked.data));
  }
  function sample() { setForm({ ...initial, startDate: "2026-09-04", leaveMonths: "12", ordinaryWageWon: "3,000,000" }); setErrors({}); setResult(null); setApplied(null); }

  return <div className="mx-auto w-full max-w-6xl flex-1 px-5 py-10 sm:px-8 sm:py-14">
    <header className="max-w-3xl"><p className="mb-3 text-sm font-semibold text-primary">노동/근로</p><h1 className="text-3xl font-bold tracking-[-0.03em] sm:text-4xl">육아휴직급여 계산기</h1><p className="mt-3 text-base leading-7 text-muted">통상임금과 육아휴직 기간으로 일반·부모 함께·한부모 특례의 월별 예상 급여를 계산합니다.</p></header>

    <form onSubmit={submit} className="mt-10 space-y-7 rounded-2xl border border-border bg-surface p-5 sm:p-8" noValidate>
      <fieldset><legend className="text-sm font-semibold">적용 유형</legend><div className="mt-3 grid gap-2 sm:grid-cols-3">{(Object.entries(schemeLabels) as [BenefitScheme,string][]).map(([key,label]) => <label key={key} className={`cursor-pointer rounded-xl border px-4 py-3 text-center text-sm font-semibold focus-within:ring-2 focus-within:ring-primary ${form.scheme === key ? "border-primary bg-primary-soft text-primary" : "border-border bg-background text-muted"}`}><input type="radio" name="scheme" value={key} className="sr-only" checked={form.scheme === key} onChange={() => update("scheme",key)} />{label}</label>)}</div><p className="mt-2 text-xs leading-5 text-muted">부모 함께 제도와 한부모 특례는 사용자가 해당 요건을 충족한다고 입력한 경우의 예상액입니다.</p></fieldset>
      <div className="grid gap-5 sm:grid-cols-2">
        <label className="text-sm font-semibold">육아휴직 시작일 <span className="text-danger">*</span><input type="date" min="2025-02-23" value={form.startDate} onChange={(e) => update("startDate",e.target.value)} aria-invalid={!!errors.startDate} className={fieldClass} />{errors.startDate && <span role="alert" className="mt-1.5 block font-normal text-danger">{errors.startDate}</span>}</label>
        <label className="text-sm font-semibold">이번 육아휴직 기간 <span className="text-danger">*</span><div className="relative"><input inputMode="numeric" value={form.leaveMonths} onChange={(e) => update("leaveMonths",e.target.value)} aria-invalid={!!errors.leaveMonths} className={`${fieldClass} pr-14`} /><span className="pointer-events-none absolute right-4 top-[1.15rem] text-sm text-muted">개월</span></div>{errors.leaveMonths && <span role="alert" className="mt-1.5 block font-normal text-danger">{errors.leaveMonths}</span>}{estimatedEnd && <span className="mt-1.5 block font-normal text-muted">예상 종료일 {formatKoreanDate(estimatedEnd)}</span>}</label>
        <label className="text-sm font-semibold">월 통상임금 <span className="text-danger">*</span><div className="relative"><input inputMode="numeric" placeholder="예: 3,000,000" value={form.ordinaryWageWon} onChange={(e) => update("ordinaryWageWon",e.target.value)} aria-invalid={!!errors.ordinaryWageWon} className={`${fieldClass} pr-12`} /><span className="pointer-events-none absolute right-4 top-[1.15rem] text-sm text-muted">원</span></div>{errors.ordinaryWageWon && <span role="alert" className="mt-1.5 block font-normal text-danger">{errors.ordinaryWageWon}</span>}</label>
        <label className="text-sm font-semibold">동일 자녀로 이미 사용한 기간<div className="relative"><input inputMode="numeric" value={form.priorLeaveMonths} onChange={(e) => update("priorLeaveMonths",e.target.value)} className={`${fieldClass} pr-14`} /><span className="pointer-events-none absolute right-4 top-[1.15rem] text-sm text-muted">개월</span></div><span className="mt-1.5 block font-normal text-muted">분할휴직이면 완전히 사용한 개월 수를 입력하세요.</span>{errors.priorLeaveMonths && <span role="alert" className="mt-1.5 block font-normal text-danger">{errors.priorLeaveMonths}</span>}</label>
      </div>

      {form.scheme === "parents-together" && <fieldset className="rounded-xl border border-border bg-background p-4 sm:p-5"><legend className="px-2 text-sm font-semibold">부모 함께 육아휴직제 정보</legend><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">자녀 생년월일 <span className="text-danger">*</span><input type="date" value={form.childBirthDate} onChange={(e) => update("childBirthDate",e.target.value)} className={fieldClass} />{errors.childBirthDate && <span role="alert" className="mt-1 block font-normal text-danger">{errors.childBirthDate}</span>}</label><label className="text-sm font-semibold">배우자 육아휴직 시작일 <span className="text-danger">*</span><input type="date" value={form.spouseStartDate} onChange={(e) => update("spouseStartDate",e.target.value)} className={fieldClass} />{errors.spouseStartDate && <span role="alert" className="mt-1 block font-normal text-danger">{errors.spouseStartDate}</span>}</label><label className="text-sm font-semibold">배우자 육아휴직 기간 <span className="text-danger">*</span><div className="relative"><input inputMode="numeric" value={form.spouseLeaveMonths} onChange={(e) => update("spouseLeaveMonths",e.target.value)} className={`${fieldClass} pr-14`} /><span className="pointer-events-none absolute right-4 top-[1.15rem] text-sm text-muted">개월</span></div>{errors.spouseLeaveMonths && <span role="alert" className="mt-1 block font-normal text-danger">{errors.spouseLeaveMonths}</span>}</label><fieldset><legend className="text-sm font-semibold">배우자 사용 상태</legend><div className="mt-2 flex gap-2">{([ ["used","사용함"], ["planned","사용 예정"] ] as const).map(([value,label]) => <label key={value} className={`flex-1 cursor-pointer rounded-xl border px-3 py-3 text-center text-sm ${form.spouseLeaveStatus === value ? "border-primary bg-primary-soft text-primary" : "border-border"}`}><input type="radio" name="spouse-status" className="sr-only" checked={form.spouseLeaveStatus === value} onChange={() => update("spouseLeaveStatus",value)} />{label}</label>)}</div>{errors.spouseLeaveStatus && <span role="alert" className="mt-1 block text-sm text-danger">{errors.spouseLeaveStatus}</span>}</fieldset></div><p className="mt-4 text-xs leading-5 text-muted">부모 모두 각자의 육아휴직 개시일에 자녀가 생후 18개월 이내여야 합니다. 휴직 기간이 서로 겹칠 필요는 없습니다.</p></fieldset>}

      {totalMonths > 12 && <fieldset className="rounded-xl border border-warning/30 bg-warning-soft p-4"><legend className="px-2 text-sm font-semibold">13~18개월 연장 요건 확인</legend><div className="mt-2 space-y-2">{([ ["both-parents","부모 모두 동일 자녀로 각각 3개월 이상 사용"], ["single-parent","한부모 근로자"], ["disabled-child","관련 기준에 해당하는 중증 장애아동의 부모"] ] as const).map(([value,label]) => <label key={value} className="flex items-start gap-3 text-sm"><input type="radio" name="extension" value={value} checked={form.extensionEligibility === value} onChange={() => update("extensionEligibility",value)} className="mt-1" /><span>{label}</span></label>)}</div>{errors.extensionEligibility && <p role="alert" className="mt-2 text-sm text-danger">{errors.extensionEligibility}</p>}<p className="mt-3 text-xs text-muted">이 선택은 행정상 자격을 확정하지 않습니다.</p></fieldset>}
      <p className="rounded-xl bg-surface-subtle px-4 py-3 text-sm leading-6 text-muted">현재 버전은 정확성이 확인된 완전한 달력 개월만 계산합니다. 한 달 미만 또는 선행 부분월이 있으면 고용센터에 확인해 주세요.</p>
      <div className="flex flex-wrap gap-3"><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">예상 급여 계산하기</button><button type="button" onClick={sample} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold">예시 입력</button><button type="button" onClick={() => { setForm(initial); setErrors({}); setResult(null); setApplied(null); }} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold text-muted">초기화</button></div>
    </form>

    <ShareActions className="mt-5" title="육아휴직급여 계산기" text={result ? `${result.leaveMonths}개월 총 예상 육아휴직급여는 ${formatWon(result.totalBenefitWon)}입니다.` : "통상임금과 휴직 기간으로 예상 육아휴직급여를 계산해 보세요."} url={baseUrl ? (result ? buildStateShareUrl(baseUrl, { f: form }) : baseUrl) : undefined} mode={result ? "result" : "calculator"} />
    <div aria-live="polite" className="mt-8 space-y-5">{result && applied && <>
      <section className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary-soft via-surface to-surface p-6 shadow-[0_20px_60px_-36px_rgba(82,112,220,.45)] sm:p-8"><p className="text-sm font-semibold text-muted">총 예상 육아휴직급여</p><p className="mt-2 text-4xl font-bold tracking-[-0.04em] text-primary tabular-nums sm:text-5xl">{formatWon(result.totalBenefitWon)}</p><p className="mt-5 font-semibold">{schemeLabels[result.scheme]} · {result.leaveMonths}개월</p><p className="mt-1 text-sm text-muted">{formatKoreanDate(result.startDate)}부터 {formatKoreanDate(result.endDate)}까지 · 월평균 {formatWon(result.averageBenefitWon)}</p>{result.conditional && <p className="mt-3 rounded-lg bg-warning-soft px-3 py-2 text-sm text-warning-foreground">배우자의 예정된 육아휴직을 전제로 한 조건부 예상액입니다.</p>}</section>
      <SectionCard title="계산 요약" icon={<Icon name="result" />}><dl className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted">적용 유형</dt><dd className="mt-1 font-semibold">{schemeLabels[result.scheme]}</dd></div><div><dt className="text-muted">특례 적용</dt><dd className="mt-1 font-semibold">{result.specialMonths ? `${result.specialMonths}개월` : "없음"}</dd></div><div><dt className="text-muted">특례 소계</dt><dd className="mt-1 font-semibold text-primary">{formatWon(result.specialSubtotalWon)}</dd></div><div><dt className="text-muted">일반 소계</dt><dd className="mt-1 font-semibold">{formatWon(result.generalSubtotalWon)}</dd></div></dl>{result.notices.map((notice) => <p key={notice} className="mt-3 rounded-lg bg-surface-subtle px-3 py-2 text-sm leading-6 text-muted">{notice}</p>)}</SectionCard>
      <SectionCard title="월별 상세 내역" icon={<Icon name="detail" />}><div className="space-y-3 sm:hidden">{result.months.map((month) => <article key={month.currentLeaveMonth} className="rounded-xl border border-border p-4"><div className="flex justify-between gap-3"><strong>{month.benefitMonth}개월째</strong><strong className="text-primary">{formatWon(month.benefitWon)}</strong></div><p className="mt-1 text-xs text-muted">{formatShortDate(month.startDate)}~{formatShortDate(month.endDate)}</p><p className="mt-3 text-sm">{month.policyLabel} · 통상임금 {month.ratePercent}%</p><p className="mt-1 text-xs text-muted">기준 {formatWon(month.baseWon)} · 상한 {formatWon(month.capWon)} · 하한 {formatWon(month.floorWon)}</p></article>)}</div><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border text-muted"><tr><th className="py-3 pr-3">급여월</th><th className="py-3 pr-3">대상 기간</th><th className="py-3 pr-3">적용 기준</th><th className="py-3 pr-3">지급률</th><th className="py-3 pr-3">상한</th><th className="py-3 text-right">예상액</th></tr></thead><tbody className="divide-y divide-border">{result.months.map((month) => <tr key={month.currentLeaveMonth}><td className="py-3 pr-3 font-semibold">{month.benefitMonth}개월째</td><td className="py-3 pr-3 tabular-nums text-muted">{formatShortDate(month.startDate)}~{formatShortDate(month.endDate)}</td><td className="py-3 pr-3">{month.policyLabel}</td><td className="py-3 pr-3">{month.ratePercent}%</td><td className="py-3 pr-3">{formatWon(month.capWon)}</td><td className="py-3 text-right font-semibold text-primary">{formatWon(month.benefitWon)}</td></tr>)}</tbody><tfoot className="border-t border-border"><tr><th colSpan={5} className="py-4">합계</th><th className="py-4 text-right text-base text-primary">{formatWon(result.totalBenefitWon)}</th></tr></tfoot></table></div></SectionCard>
      <SectionCard title="계산 방법" icon={<Icon name="formula" />}><div className="space-y-5 text-sm leading-6"><div><p className="font-semibold">1. 급여월 순번 결정</p><p className="text-muted">이전 사용 {result.priorLeaveMonths}개월 + 이번 휴직 월 순서로 동일 자녀 기준 {result.priorLeaveMonths + 1}개월째부터 계산합니다.</p></div><div><p className="font-semibold">2. 월 지급 기준 적용</p><p className="text-muted">일반 1~3개월은 통상임금 100%·상한 250만원, 4~6개월은 100%·상한 200만원, 7개월 이후는 80%·상한 160만원이며 하한은 70만원입니다.</p></div><div><p className="font-semibold">3. 상·하한 확정</p><p className="text-muted">월 예상액 = min(월 상한, max(월 하한, 통상임금 × 지급률))</p></div><div><p className="font-semibold">4. 월별 금액 합산</p><p className="text-muted">{result.months.map((month) => formatWon(month.benefitWon).replace("원","")).join(" + ")} = <strong className="text-foreground">{formatWon(result.totalBenefitWon)}</strong></p></div></div></SectionCard>
      <SectionCard title="자격 및 정책 안내" icon={<Icon name="info" />}><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-muted"><li>휴직 시작 전 피보험단위기간 180일 이상 등 별도 수급요건을 확인해야 합니다.</li><li>사업주 지급 금품, 휴직 중 취업·소득과 실제 배우자 사용기간에 따라 지급액이 달라질 수 있습니다.</li><li>사후지급금 25%를 유보하지 않는 2025년 이후 현행 방식을 적용했습니다.</li><li>정책 기준 {PARENTAL_LEAVE_POLICY_REVIEWED_AT} · 다음 재검토 {PARENTAL_LEAVE_POLICY_NEXT_REVIEW}</li></ul></SectionCard>
    </>}</div>
    <section className="mt-12 rounded-2xl bg-surface-subtle p-6 text-sm leading-7 text-muted">이 계산기는 수급자격을 확정하지 않는 참고용 도구입니다. 실제 지급 여부와 금액은 육아휴직 확인서, 고용보험 이력과 관할 고용센터의 심사 결과가 우선합니다. 입력값은 저장하거나 서버로 전송하지 않습니다.</section>
    <div className="mt-5"><FaqAccordion items={parentalLeaveBenefitFaqItems.map((item) => ({ ...item, answer: [...item.answer] }))} /></div>
  </div>;
}
