"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {FaqAccordion} from "@/components/calculator/FaqAccordion";
import {SectionCard} from "@/components/calculator/SectionCard";
import {ShareActions} from "@/components/calculator/ShareActions";
import {buildStateShareUrl,decodeShareState} from "@/src/lib/share";
import { kakaoShareAdapter } from "@/src/lib/kakao-share";
import {ageCalculatorFaqItems} from "./content";
import {formatCalendarAge,formatDday,formatKoreanDate,formatShortDate,weekdayLabels} from "./formatting";
import {calculateAge} from "./logic";
import type {AgeCalculatorResult} from "./types";
import {validateAgeInput,type RawAgeCalculatorInput} from "./validation";

function todayInKorea(){const parts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=(type:string)=>parts.find((p)=>p.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`;}
function Icon({name}:{name:"calendar"|"info"|"compare"|"formula"}){const paths={calendar:<path d="M6 3v3m12-3v3M4 9h16M5 5h14v16H5z"/>,info:<path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-11v6m0-10h.01"/>,compare:<path d="M7 7h13m-4-4 4 4-4 4M17 17H4m4-4-4 4 4 4"/>,formula:<path d="M5 5h6L7 12l4 7H5m10-9h5m-2.5-2.5v5"/>};return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>}
const fieldClass="mt-2 block min-w-0 w-full rounded-xl border border-border bg-background px-3.5 py-3 outline-none focus:border-primary focus:ring-4 focus:ring-primary/10";

export default function AgeCalculatorUi(){const today=todayInKorea();const initial:RawAgeCalculatorInput={birthDate:"",referenceDate:today};const[form,setForm]=useState(initial);const[errors,setErrors]=useState<Record<string,string>>({});const[result,setResult]=useState<AgeCalculatorResult|null>(null);const[baseUrl,setBaseUrl]=useState("");
  useEffect(()=>{const timer=window.setTimeout(()=>{const current=new URL(window.location.href);current.search="";current.hash="";setBaseUrl(current.toString());const encoded=new URLSearchParams(window.location.search).get("s");if(!encoded)return;const state=decodeShareState(encoded);if(!state||typeof state!=="object")return;const candidate=state as Record<string,unknown>;if(typeof candidate.b!=="string"||typeof candidate.r!=="string")return;const checked=validateAgeInput({birthDate:candidate.b,referenceDate:candidate.r});if(!checked.success)return;setForm(checked.data);setErrors({});setResult(calculateAge(checked.data));},0);return()=>window.clearTimeout(timer)},[]);
  function update(key:keyof RawAgeCalculatorInput,value:string){setForm((p)=>({...p,[key]:value}));setResult(null);}
  function submit(e:React.FormEvent){e.preventDefault();const checked=validateAgeInput(form);if(!checked.success){setErrors(Object.fromEntries(checked.errors.map((x)=>[x.field,x.message])));setResult(null);return}setErrors({});setResult(calculateAge(checked.data));}
  function sample(){setForm({birthDate:"2014-09-16",referenceDate:today});setErrors({});setResult(null);}
  return <div className="mx-auto w-full max-w-6xl flex-1 px-5 py-10 sm:px-8 sm:py-14">
    <header className="max-w-3xl"><Link href="/categories/date" className="mb-3 inline-block text-sm font-semibold text-primary hover:underline">날짜</Link><h1 className="text-3xl font-bold tracking-[-0.03em] sm:text-4xl">만 나이 계산기</h1><p className="mt-3 text-base leading-7 text-muted">생년월일과 기준일로 만 나이, 정확한 경과기간, 다음 생일과 음력 설날 기준 띠를 계산합니다.</p></header>
    <form onSubmit={submit} noValidate className="mt-10 space-y-7 rounded-2xl border border-border bg-surface p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">생년월일 <span className="text-danger">*</span><input type="date" min="1900-01-01" max="2200-12-31" value={form.birthDate} onChange={(e)=>update("birthDate",e.target.value)} aria-invalid={!!errors.birthDate} className={fieldClass}/><span className="mt-1.5 block font-normal text-muted">주민등록상 생년월일을 입력하세요.</span>{errors.birthDate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.birthDate}</span>}</label><label className="text-sm font-semibold">기준일 <span className="text-danger">*</span><input type="date" min="1900-01-01" max="2200-12-31" value={form.referenceDate} onChange={(e)=>update("referenceDate",e.target.value)} aria-invalid={!!errors.referenceDate} className={fieldClass}/><span className="mt-1.5 block font-normal text-muted">이 날짜를 기준으로 나이를 계산합니다.</span>{errors.referenceDate&&<span role="alert" className="mt-1 block font-normal text-danger">{errors.referenceDate}</span>}</label></div><div className="flex flex-wrap gap-3"><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">만 나이 계산하기</button><button type="button" onClick={sample} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold">오늘 기준 예시</button><button type="button" onClick={()=>{setForm(initial);setErrors({});setResult(null)}} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold text-muted">초기화</button></div></form>
    <ShareActions className="mt-5" title="만 나이 계산기" text={result?`${formatKoreanDate(result.referenceDate)} 기준 만 ${result.fullAge}세입니다.`:"생년월일과 기준일로 만 나이와 다음 생일까지 계산해 보세요."} url={baseUrl?(result?buildStateShareUrl(baseUrl,{b:result.birthDate,r:result.referenceDate}):baseUrl):undefined} mode={result?"result":"calculator"} onKakaoShare={kakaoShareAdapter}/>
    <div aria-live="polite" className="mt-8 space-y-5">{result&&<><section className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary-soft via-surface to-surface p-6 shadow-[0_20px_60px_-36px_rgba(82,112,220,.45)] sm:p-8"><p className="text-sm font-semibold text-muted">기준일 현재 만 나이</p><p className="mt-2 text-4xl font-bold tracking-[-0.04em] text-primary sm:text-5xl">만 {result.fullAge}세</p><p className="mt-5 text-lg font-semibold">정확히 {formatCalendarAge(result.calendarAge)}</p>{result.fullAge===0&&<p className="mt-1 text-sm text-muted">1세 미만은 {result.calendarAge.months}개월 {result.calendarAge.days}일로도 표시할 수 있습니다.</p>}{result.birthdayState==="today"&&<p className="mt-3 inline-flex rounded-full bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground">기준일이 생일입니다</p>}</section>
      <SectionCard title="입력 정보와 추가 결과" icon={<Icon name="calendar"/>}><dl className="grid gap-x-8 gap-y-5 text-sm sm:grid-cols-2"><div><dt className="text-muted">생년월일</dt><dd className="mt-1 font-semibold">{formatKoreanDate(result.birthDate)} ({weekdayLabels[result.birthWeekday]})</dd></div><div><dt className="text-muted">기준일</dt><dd className="mt-1 font-semibold">{formatKoreanDate(result.referenceDate)} ({weekdayLabels[result.referenceWeekday]})</dd></div><div><dt className="text-muted">태어난 지</dt><dd className="mt-1 text-lg font-semibold text-primary">{result.daysSinceBirth.toLocaleString("ko-KR")}일</dd></div><div><dt className="text-muted">{result.birthdayState==="today"?"오늘 생일":"다음 생일"}</dt><dd className="mt-1 text-lg font-semibold">{formatKoreanDate(result.nextBirthday)} · {formatDday(result.daysUntilBirthday)}</dd></div></dl></SectionCard>
      <SectionCard title="나이 종류 비교" icon={<Icon name="compare"/>}><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-primary/30 bg-primary-soft p-4"><p className="text-sm text-muted">법적 기본</p><p className="mt-1 text-xl font-bold text-primary">만 {result.fullAge}세</p></div><div className="rounded-xl border border-border bg-background p-4"><p className="text-sm text-muted">과거 한국식 세는나이</p><p className="mt-1 text-xl font-bold">{result.koreanCountingAge}세</p></div><div className="rounded-xl border border-border bg-background p-4"><p className="text-sm text-muted">연 나이</p><p className="mt-1 text-xl font-bold">{result.yearAge}세</p></div></div><p className="mt-4 text-xs leading-5 text-muted">별도 규정이 없다면 법률·행정상 나이는 만 나이가 원칙입니다. 연 나이는 일부 개별 법령에서만 사용합니다.</p></SectionCard>
      <SectionCard title="띠·간지 정보" icon={<Icon name="info"/>}>{result.zodiac?<div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted">음력 설날 기준</p><p className="mt-1 text-2xl font-bold text-primary">{result.zodiac.displayName}</p></div><p className="text-right font-semibold">{result.zodiac.ganzhiKorean} ({result.zodiac.ganzhiChinese})</p></div><dl className="mt-5 grid gap-3 rounded-xl bg-surface-subtle p-4 text-sm sm:grid-cols-3"><div><dt className="text-muted">음력년</dt><dd className="mt-1 font-semibold">{result.zodiac.lunarYear}년</dd></div><div><dt className="text-muted">오행</dt><dd className="mt-1 font-semibold">{result.zodiac.element}</dd></div><div><dt className="text-muted">십이지</dt><dd className="mt-1 font-semibold">{result.zodiac.animal} ({result.zodiac.earthlyBranch})</dd></div></dl><p className="mt-4 text-xs leading-5 text-muted">‘황금’은 토(土)의 황색 계열을 친숙하게 표현한 문화적 별칭이며 금(金) 오행을 뜻하지 않습니다. 사주에서 쓰는 입춘 기준과는 결과가 다를 수 있습니다.</p></div>:<p className="text-sm leading-6 text-muted">띠·간지는 1900년부터 2050년까지 검증된 한국 음력 데이터 범위에서만 제공합니다. 만 나이 결과에는 영향이 없습니다.</p>}</SectionCard>
      <SectionCard title="계산 방법" icon={<Icon name="formula"/>}><ol className="space-y-4 text-sm leading-6"><li><p className="font-semibold">1. 올해 생일 통과 여부</p><p className="text-muted">{formatShortDate(result.referenceDate)} 기준 올해 생일을 {result.birthdayState==="before"?"아직 지나지 않았습니다.":result.birthdayState==="today"?"맞았습니다.":"지났습니다."}</p></li><li><p className="font-semibold">2. 만 나이</p><p className="text-muted">기준연도 − 출생연도{result.birthdayState==="before"?" − 1":""} = {result.fullAge}세</p></li><li><p className="font-semibold">3. 정확한 경과기간</p><p className="text-muted">완전한 연·월을 차례로 계산한 뒤 남은 날짜 경계를 더해 {formatCalendarAge(result.calendarAge)}입니다.</p></li><li><p className="font-semibold">4. 띠</p><p className="text-muted">양력 생년월일을 한국 음력으로 변환하고 음력 설날을 경계로 연간지를 정합니다.</p></li></ol></SectionCard>
      <SectionCard title="법적 기준" icon={<Icon name="info"/>}><p className="text-sm leading-6 text-muted">민법 제158조와 행정기본법 제7조의2에 따라 나이는 출생일을 산입해 만 나이로 계산하고 연수로 표시합니다. 다만 다른 법령이 특별한 기준을 정하면 그 규정이 우선합니다. 2월 29일생은 평년에 2월 말일을 대응 생일로 계산합니다.</p></SectionCard></>}</div>
    <section className="mt-12 rounded-2xl bg-surface-subtle p-6 text-sm leading-7 text-muted">띠는 한국 음력의 설날을 경계로 한 생활문화 정보이며 운세나 법적 자격을 판단하지 않습니다. 입력값은 저장하거나 서버로 전송하지 않습니다.</section><div className="mt-5"><FaqAccordion items={ageCalculatorFaqItems.map((x)=>({...x,answer:[...x.answer]}))}/></div>
  </div>}
