import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,describe,expect,it} from "vitest";
import {buildStateShareUrl,decodeShareState} from "@/src/lib/share";
import AgeCalculatorUi from "./ui";
describe("AgeCalculatorUi",()=>{
  afterEach(()=>window.history.replaceState({},"","/"));
  it("생년월일 누락 오류",()=>{render(<AgeCalculatorUi/>);fireEvent.click(screen.getByRole("button",{name:"만 나이 계산하기"}));expect(screen.getByText("생년월일을 입력해 주세요.")).toHaveAttribute("role","alert")});
  it("예시 날짜 결과",()=>{render(<AgeCalculatorUi/>);fireEvent.change(screen.getByLabelText(/생년월일/),{target:{value:"2014-09-16"}});fireEvent.change(screen.getByLabelText(/기준일/),{target:{value:"2026-09-05"}});fireEvent.click(screen.getByRole("button",{name:"만 나이 계산하기"}));expect(screen.getAllByText("만 11세")).toHaveLength(2);expect(screen.getByText("정확히 11년 11개월 20일")).toBeInTheDocument();expect(screen.getByText(/푸른 말띠/)).toBeInTheDocument()});
  it("2018 설날 황금 개띠",()=>{render(<AgeCalculatorUi/>);fireEvent.change(screen.getByLabelText(/생년월일/),{target:{value:"2018-02-16"}});fireEvent.change(screen.getByLabelText(/기준일/),{target:{value:"2026-09-05"}});fireEvent.click(screen.getByRole("button",{name:"만 나이 계산하기"}));expect(screen.getByText("황금 개띠")).toBeInTheDocument();expect(screen.getByText(/무술년/)).toBeInTheDocument()});
  it("계산 후 Base64URL 결과 공유 상태로 전환",async()=>{render(<AgeCalculatorUi/>);fireEvent.change(screen.getByLabelText(/생년월일/),{target:{value:"2014-09-16"}});fireEvent.change(screen.getByLabelText(/기준일/),{target:{value:"2026-09-05"}});fireEvent.click(screen.getByRole("button",{name:"만 나이 계산하기"}));const section=screen.getByRole("region",{name:"계산 결과 공유"});const xLink=section.querySelector('a[aria-label="X로 공유"]');expect(xLink).not.toBeNull();await waitFor(()=>{const intent=new URL(xLink!.getAttribute("href")!);const shared=intent.searchParams.get("url");expect(shared).toBeTruthy();const resultUrl=new URL(shared!);expect([...resultUrl.searchParams.keys()]).toEqual(["s"]);expect(decodeShareState(resultUrl.searchParams.get("s")!)).toEqual({b:"2014-09-16",r:"2026-09-05"});expect(intent.searchParams.get("text")).toContain("만 11세")})});
  it("공유 URL 입력을 검증하고 결과를 자동 복원",async()=>{const url=buildStateShareUrl(window.location.href,{b:"2014-09-16",r:"2026-09-05"});window.history.replaceState({},"",url);render(<AgeCalculatorUi/>);await waitFor(()=>expect(screen.getAllByText("만 11세")).toHaveLength(2));expect(screen.getByLabelText(/생년월일/)).toHaveValue("2014-09-16");expect(screen.getByRole("region",{name:"계산 결과 공유"})).toBeInTheDocument()});
  it("손상된 공유 상태는 오류 없이 기본 화면으로 처리",async()=>{window.history.replaceState({},"","/?s=broken-state");render(<AgeCalculatorUi/>);await waitFor(()=>expect(screen.getByRole("region",{name:"계산기 공유"})).toBeInTheDocument());expect(screen.queryByText(/기준일 현재 만 나이/)).not.toBeInTheDocument()});
});
